apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: e2e-tests-
    labels:
        app: ai-incident-assistant
        test-type: e2e
spec:
    serviceAccountName: argo-workflow
    entrypoint: e2e-test-suite
    
    # Input parameters
    arguments:
        parameters:
            - name: image_tag
              value: "latest"
            - name: staging_url
              value: "http://staging.174.138.120.13.nip.io"
            - name: browser
              value: "chromium"
        
    # TTL for workflow cleanup
    ttlStrategy:
        secondsAfterCompletion: 86400  # 24 hours
        secondsAfterSuccess: 43200      # 12 hours
        secondsAfterFailure: 172800     # 48 hours
        
    templates:
        # ============================================
        # Main E2E Test Suite
        # ============================================
        - name: e2e-test-suite
          dag:
              tasks:
                  - name: setup
                    template: setup-tests
                    
                  - name: health-check
                    template: health-check
                    dependencies: [setup]
                    
                  - name: e2e-tests
                    template: run-e2e-tests
                    dependencies: [health-check]
                    
                  - name: collect-results
                    template: collect-results
                    dependencies: [e2e-tests]

        # ============================================
        # Setup Template
        # ============================================
        - name: setup-tests
          container:
              image: alpine:3.18
              command: [sh, -c]
              args:
                  - |
                      echo "ðŸ§ª E2E Test Setup"
                      echo "================================"
                      echo "Image Tag: {{workflow.parameters.image_tag}}"
                      echo "Staging URL: {{workflow.parameters.staging_url}}"
                      echo "Browser: {{workflow.parameters.browser}}"
                      echo "================================"
                      echo "Setup complete!"

        # ============================================
        # Health Check Template
        # ============================================
        - name: health-check
          container:
              image: curlimages/curl:8.5.0
              command: [sh, -c]
              args:
                  - |
                      echo "ðŸ¥ Running health checks..."
                      
                      # Check frontend
                      echo "Checking frontend..."
                      for i in $(seq 1 10); do
                        if curl -sf "{{workflow.parameters.staging_url}}" > /dev/null; then
                          echo "âœ… Frontend is healthy"
                          break
                        fi
                        echo "Waiting for frontend... ($i/10)"
                        sleep 5
                      done
                      
                      # Check backend API
                      echo "Checking backend API..."
                      for i in $(seq 1 10); do
                        if curl -sf "{{workflow.parameters.staging_url}}/api/health" > /dev/null; then
                          echo "âœ… Backend API is healthy"
                          break
                        fi
                        echo "Waiting for backend... ($i/10)"
                        sleep 5
                      done
                      
                      echo "âœ… All health checks passed!"
          retryStrategy:
              limit: 3
              retryPolicy: "Always"

        # ============================================
        # E2E Tests with Playwright
        # ============================================
        - name: run-e2e-tests
          script:
              image: mcr.microsoft.com/playwright:v1.57.0-jammy
              command: [bash]
              source: |
                  #!/bin/bash
                  set -e
                  
                  echo "ðŸŽ­ Running E2E Tests"
                  
                  # Clone repository to get test files
                  git clone https://github.com/0019-KDU/cloud-native-ci-cd-blueprint.git /workspace
                  cd /workspace/tests/e2e
                  
                  # Install dependencies
                  npm ci
                  
                  # Set staging URL
                  export BASE_URL="{{workflow.parameters.staging_url}}"
                  
                  # Run Playwright tests
                  npx playwright test \
                    --project={{workflow.parameters.browser}} \
                    specs/*.spec.js \
                    --reporter=list
                  
                  echo "âœ… E2E tests completed successfully!"
              env:
                  - name: BASE_URL
                    value: "{{workflow.parameters.staging_url}}"
                  - name: CI
                    value: "true"
              resources:
                  requests:
                      memory: "1Gi"
                      cpu: "500m"
                  limits:
                      memory: "2Gi"
                      cpu: "1000m"

        # ============================================
        # Collect Results
        # ============================================
        - name: collect-results
          container:
              image: alpine:3.18
              command: [sh, -c]
              args:
                  - |
                      echo "ðŸ“Š E2E Test Results Summary"
                      echo "================================"
                      echo "Image Tag: {{workflow.parameters.image_tag}}"
                      echo "Staging URL: {{workflow.parameters.staging_url}}"
                      echo "================================"
                      echo ""
                      echo "âœ… All E2E tests completed successfully!"
                      echo ""
                      echo "Test artifacts have been saved."